version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 2
  reviewers:
  - Morendil
  - sandcha
  - fpagnoux
  labels:
  - kind:dependencies
  ignore:
  - dependency-name: autopep8
    versions:
    - 1.5.5
