language: python
python: "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:pythonxy/pythonxy-devel -y  # For Pandas
  - sudo add-apt-repository ppa:pylab/stable -y  # For SciPY
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy python-yaml
install:
  - pip install flake8  # Not yet available in Debian stable
  - pip install -r requirements.txt
#  - pip install -e git+https://github.com/openfisca/openfisca-france-data.git#egg=OpenFisca-France-Data  # For test_from_taxipp
script: make test-ci
