addons:
  apt:
    packages:
    - python-numpy
    - python-yaml
    - python-scipy
install:
  - pip install flake8  # Not yet available in Ubuntu precise (https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise)
  - pip install -r requirements.txt
language: python
python: "2.7"
script: bash run-travis-tests.sh
sudo: false
virtualenv:
  system_site_packages: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_f6aff9134f80_key -iv $encrypted_f6aff9134f80_iv -in openfisca_bot.enc -out openfisca_bot -d
deploy:
  - provider: script
    skip_cleanup: true
    script: ./release.sh
    on:
      branch: master
  - provider: pypi
    user: openfisca-bot
    password:
      secure: TysRV2ljC0p1LaWwHiBuFNBz7hjAFK7LDV0OL/7L31TZebxKi2a5MGg42ugqNxjeW30+6mL/g5FbeSDkskpFGC4W0vE+xvSORDPhas+NWbt/7Mb97vHjGguawguUuCCOgmX705BZxJyxGdv8MpaJmELZxV4stJ51Qw3Y1iLmz7M=
    distributions: "bdist_wheel"
    on:
      tags: true
