language: python
python: "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:pythonxy/pythonxy-devel -y  # For Pandas
  - sudo add-apt-repository ppa:pylab/stable -y  # For SciPY
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pandas
  - sudo apt-get install -qq python-scipy
install:
  - pip install isodate  # For Biryani1 datetimeconv
  - pip install -e git+https://github.com/etalab/biryani.git@biryani1#egg=Biryani1  # For OpenFisca-Core
  - pip install -e git+https://github.com/openfisca/openfisca-core.git#egg=OpenFisca-Core
  - pip install -r requirements.txt
script: nosetests openfisca_france/tests
