addons:
  apt:
    packages:
    - python-numpy
    - python-yaml
install:
  - pip install flake8  # Not yet available in Ubuntu precise (https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise)
  - pip install -r requirements.txt
language: python
python: "2.7"
script: make test-ci
virtualenv:
  system_site_packages: true
