sudo: false # Use new Travis container-based infrastructure
language: python
python: 2.7
addons:
  ssh_known_hosts: api.openfisca.fr
cache: pip
install:
  - pip install --upgrade pip wheel  # pip >= 8.0 needed to be compatible with "manylinux" wheels, used by numpy >= 1.11
  - pip install --editable ".[inversion_revenus, test]"
script: ./travis-run-tests.sh
before_deploy:
  - python setup.py compile_catalog
  - rm -f ./openfisca_bot ./deploy-api
  - openssl aes-256-cbc -K $encrypted_f6aff9134f80_key -iv $encrypted_f6aff9134f80_iv -in openfisca_bot.enc -out openfisca_bot -d
  - openssl aes-256-cbc -K $encrypted_a272d9ca0751_key -iv $encrypted_a272d9ca0751_iv -in deploy-api.enc -out deploy-api -d
  - eval "$(ssh-agent -s)"
  - chmod 400 ./openfisca_bot ./deploy-api
  - ssh-add ./openfisca_bot ./deploy-api
deploy:
  - provider: script
    skip_cleanup: true
    script: ./travis-release-tag.sh
    on:
      branch: master
  - provider: pypi
    user: openfisca-bot
    password:
      secure: u/4GonOlBu3j486GOu28nEOjnIJjWV7/K6UHLYpIGPWhkRch0gq4vk8F17lrp94LFFRyqnNJUTsekFxGuws1lrtWSZEqofU438Wu5ihwYjAVFT3DSOkbqlS47kTqwPULsKLykFg9/mUyH/ONHAFzWW+cd+xM/qRSagIQ2lvpmXI=
    distributions: "bdist_wheel"
    on:
      tags: true
  - provider: script
    script: ssh deploy-api@api.openfisca.fr
    on:
      tags: true
