description: Taux forfaitaire spécial appliqué sous conditions (article 200 A, 2bis, du CGI) aux plus-values en report d'imposition et dont le report a expiré.
values:
  2016-01-01:
    value: 0.19
metadata:
  unit: /1
  reference:
    href: https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006069577&idArticle=LEGIARTI000026946928&dateTexte=&categorieLien=id
