description: Impôt sur les plus values à taux forfaitaires
metadata:
  reference:
    href: https://www.ipp.eu/outils/baremes-ipp/
imposition_des_plus_values_mobilieres_levees_d_options_attribuees_depuis_27_4_2000_cessions_realisees_moins_de_deux_ans_apres_la_levee:
  metadata:
    reference:
      href: https://www.ipp.eu/outils/baremes-ipp/
  seuil_tranche_superieure:
    metadata:
      reference:
        href: https://www.ipp.eu/outils/baremes-ipp/
      unit: currency
    2000-01-01:
      value: 1000000
    2001-01-01:
      value: 152000
    2009-01-01:
      value: 152500
    2013-01-01:
      value: null
  taux_tranche_inferieure:
    metadata:
      reference:
        href: https://www.ipp.eu/outils/baremes-ipp/
      unit: /1
    1995-01-01:
      value: 0.3
    2013-01-01:
      value: null
  taux_tranche_superieure:
    metadata:
      reference:
        href: https://www.ipp.eu/outils/baremes-ipp/
      unit: /1
    2000-01-01:
      value: 0.4
    2010-01-01:
      value: 0.41
    2013-01-01:
      value: null
pea:
  metadata:
    reference:
      href: https://www.ipp.eu/outils/baremes-ipp/
  taux_avant_2_ans:
    description: Clôture PEA avant 2 ans (3VM)
    metadata:
      reference:
        href: https://www.ipp.eu/outils/baremes-ipp/
      unit: /1
    1991-01-01:
      value: 0.225
  taux_posterieur:
    metadata:
      reference:
        href: https://www.ipp.eu/outils/baremes-ipp/
      unit: /1
    1978-01-01:
      value: 0.15
    1984-01-01:
      value: 0.16
    2012-01-01:
      value: 0.19
pea2:
  description: Clôture PEA ou PEA-PME entre 2 ans et 5 ans (3VT)
  metadata:
    reference:
      title: openfisca
    unit: /1
  2012-01-01:
    value: 0.19
pvce:
  description: Plus value de cession (RPNS) 16%
  metadata:
    reference:
      title: openfisca
    unit: /1
  2002-01-01:
    value: 0.16
  2017-01-01:
    value: 0.128
seuil_d_imposition:
  metadata:
    reference:
      href: https://www.ipp.eu/outils/baremes-ipp/
    unit: currency
  1978-01-01:
    value: 150000
  1980-01-01:
    value: 168000
  1981-01-01:
    value: 190700
  1984-01-01:
    value: 265000
  1985-01-01:
    value: 272000
  1986-01-01:
    value: 281000
  1988-01-01:
    value: 298000
  1989-01-01:
    value: 307600
  1990-01-01:
    value: 316900
  1991-01-01:
    value: 325800
  1994-01-01:
    value: 336700
  1995-01-01:
    value: 342800
  1996-01-01:
    value: 200000
  1997-01-01:
    value: 100000
  1998-01-01:
    value: 50000
  2001-01-01:
    value: 7650
  2002-01-01:
    value: 15000
  2007-01-01:
    value: 20000
  2008-01-01:
    value: 25000
  2009-01-01:
    value: 25730
  2010-01-01:
    value: 25830
  2011-01-01:
    value: null
taux:
  metadata:
    reference:
      href: https://www.ipp.eu/outils/baremes-ipp/
    unit: /1
  1978-01-01:
    value: 0.15
  1984-01-01:
    value: 0.16
  2008-01-01:
    value: 0.18
  2011-01-01:
    value: 0.19
  2012-01-01:
    value: 0.24
  2013-01-01:
    value: null
taux_plus_values_bspce:
  description: Taux général de taxation des cessions de bons de souscription de parts de créateur d'entreprise (BSPCE).
  metadata:
    reference:
      title: openfisca
    unit: /1
  2012-01-01:
    value: 0.19
taux_plus_values_bspce_conditionnel:
  description: Taux spécial de taxation des cessions de bons de souscription de parts de créateur d'entreprise (BSPCE). Ce taux est applicable si, à la date de cession des titres, vous exercez votre activité dans la société depuis moins de trois ans ou si, n’étant plus salarié de la société à la même date, vous y avez exercé votre activité pendant moins de trois ans.
  metadata:
    reference:
      title: openfisca
    unit: /1
  2012-01-01:
    value: 0.3
taux_plus_values_entc:
  description: Taux forfaitaire d'imposition sur les profits sur instruments financiers dans des ETNC
  metadata:
    reference:
      href: https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000037526716&cidTexte=LEGITEXT000006069577&categorieLien=id&dateTexte=
    unit: /1
  2018-01-01:
    value: 0.5
taux_plus_values_report:
  description: Taux forfaitaire général appliqué aux plus-values en report d'imposition et dont le report a expiré.
  metadata:
    reference:
      title: openfisca
    unit: /1
  2016-01-01:
    value: 0.24
taux_plus_values_report_conditionnel:
  description: Taux forfaitaire spécial appliqué sous conditions (article 200 A, 2bis, du CGI) aux plus-values en report d'imposition et dont le report a expiré.
  metadata:
    reference:
      href: https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006069577&idArticle=LEGIARTI000026946928&dateTexte=&categorieLien=id
    unit: /1
  2016-01-01:
    value: 0.19
taux_pv_entrep:
  description: Cessions titres réalisées par un entrepreneur
  metadata:
    reference:
      title: openfisca
    unit: /1
  2012-01-01:
    value: 0.19
  2013-01-01:
    value: null
taux_pv_mob_pro:
  description: Capital risque (VL)
  metadata:
    reference:
      title: openfisca
    unit: /1
  2002-01-01:
    value: 0.16
  2008-01-01:
    value: 0.18
  2011-01-01:
    value: 0.19
  2012-01-01:
    value: 0.24
  2013-01-01: expected
taux1:
  description: Plus values de cession de valeurs mobilières
  metadata:
    reference:
      title: openfisca
    unit: /1
  2002-01-01:
    value: 0.16
  2008-01-01:
    value: 0.18
  2011-01-01:
    value: 0.19
  2012-01-01:
    value: 0.24
  2013-01-01: expected
taux2:
  description: Actions gratuites 18%
  metadata:
    reference:
      title: openfisca
    unit: /1
  2008-01-01:
    value: 0.18
taux3:
  description: Actions gratuites 30%
  metadata:
    reference:
      title: openfisca
    unit: /1
  1995-01-01:
    value: 0.3
taux4:
  description: Actions gratuites 40%
  metadata:
    reference:
      title: openfisca
    unit: /1
  2000-01-01:
    value: 0.4
  2010-01-01:
    value: 0.41
