name: Validate YAML

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  validate_yaml:
    uses: tax-benefit/actions/.github/workflows/validate_yaml.yml@v1
    with:
      parameters_path: "openfisca_france/parameters"
    secrets:
      token: ${{ secrets.CONTROL_CENTER_TOKEN }}
